apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webapp
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webapp
  template:
    metadata:
      labels:
        app: nginx-webapp
    spec:
      containers:
      - name: nginx
        image: nginx-webapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-webapp-svc
  namespace: webapp
spec:
  selector:
    app: nginx-webapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 8083
